<<<<<<< HEAD
name: zenith-mails-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
<<<<<<< HEAD
        
=======
      - name: Insall pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
>>>>>>> 7ac94a1 (fix ci)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'
<<<<<<< HEAD
          cache : 'pnpm'
      - name: Insall pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
=======
          cache: 'pnpm'
>>>>>>> 7ac94a1 (fix ci)
      - name: Install SST
        uses: anasmohammed361/action-sst@main

      - name: Install dependencies
        run: pnpm install
<<<<<<< HEAD
      - name: Deploy
        run: sst deploy --stage=production
=======

      - run: sst deploy --stage=production
>>>>>>> 7ac94a1 (fix ci)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
=======
>>>>>>> c8fd889 (fix ci)
